[loadI 100 => r4; loadI 1024 => r2]
[store r4 => r2; loadI 200 => r3]
[loadI 1024 => r0; nop]
[store r3 => r0; nop]
[nop; nop]
[nop; nop]
[nop; nop]
[nop; nop]
[load r2 => r1; nop]
[nop; nop]
[nop; nop]
[nop; nop]
[nop; nop]
[store r1 => r0; nop]
[nop; nop]
[nop; nop]
[nop; nop]
[nop; nop]
[output 1024; nop]
